[package]
name = "bril2c"
version = "0.1.0"
edition = "2024"

[dependencies]
bril-rs = { git = "https://github.com/sampsyo/bril", package = "bril-rs", features = ["float", "memory"] }
serde_json = "1.0"
